package interfaz;
import java.util.Observer;
import java.util.Observable;
import dominio.Funcionario;
import dominio.Sistema;
import javax.swing.JOptionPane;

/*
 * Trabajo realizado por 
 * (333503) Daniel López
 * (372277) Lautaro Moreno
 */
public class DatosFuncionarios extends javax.swing.JFrame implements Observer{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DatosFuncionarios.class.getName());

        private Sistema modelo;
        
    public DatosFuncionarios(Sistema modelo) {
        this.modelo = modelo;
        this.modelo.addObserver(this);
        initComponents();
        objetoAPantalla();
        
        lstFuncionarios.addListSelectionListener(e -> lstFuncionariosValueChanged(e));
    }
    
    private void objetoAPantalla(){
        java.util.ArrayList<Funcionario> lista = this.modelo.getFuncionarios();
        lista.sort((f1,f2) -> Integer.compare(f2.getNroFuncionario(),f1.getNroFuncionario()));
        lstFuncionarios.setListData(lista.toArray());
    }
    
    @Override
   public void update (Observable o, Object arg){
       objetoAPantalla();
   }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreF = new javax.swing.JTextField();
        txtCelularF = new javax.swing.JTextField();
        txtNumeroF = new javax.swing.JTextField();
        txtAnioIngresoF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFuncionarios = new javax.swing.JList();
        BtnAgregarFuncionario = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Lista de Funcionarios");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(174, 6, 435, 45);

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(44, 62, 70, 16);

        jLabel3.setText("Celular: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(44, 107, 70, 16);

        jLabel4.setText("Nro de Funcionario");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(44, 145, 120, 16);

        jLabel5.setText("Año de Ingreso");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(44, 184, 110, 16);

        txtNombreF.addActionListener(this::txtNombreFActionPerformed);
        jPanel1.add(txtNombreF);
        txtNombreF.setBounds(106, 57, 233, 26);
        jPanel1.add(txtCelularF);
        txtCelularF.setBounds(106, 102, 233, 26);
        jPanel1.add(txtNumeroF);
        txtNumeroF.setBounds(170, 140, 169, 26);
        jPanel1.add(txtAnioIngresoF);
        txtAnioIngresoF.setBounds(170, 184, 169, 26);

        lstFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstFuncionarios);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(351, 57, 234, 203);

        BtnAgregarFuncionario.setText("Agregar");
        BtnAgregarFuncionario.addActionListener(this::BtnAgregarFuncionarioActionPerformed);
        jPanel1.add(BtnAgregarFuncionario);
        BtnAgregarFuncionario.setBounds(390, 310, 90, 27);

        btnSalir.setText("Cancelar");
        btnSalir.addActionListener(this::btnSalirActionPerformed);
        jPanel1.add(btnSalir);
        btnSalir.setBounds(490, 310, 93, 27);
        jPanel1.add(txtMensaje);
        txtMensaje.setBounds(124, 260, 0, 0);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 380);

        setBounds(0, 0, 637, 383);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreFActionPerformed

    private void BtnAgregarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarFuncionarioActionPerformed
        String nombre = txtNombreF.getText();
        String celular = txtCelularF.getText();
        String nroFuncionario = txtNumeroF.getText();
        String anioIngreso = txtAnioIngresoF.getText();
        
        boolean datosValidos = true;
        txtMensaje.setText("");
        
        if(this.modelo.textoVacio(nombre) ||
           this.modelo.textoVacio(celular) ||
           this.modelo.textoVacio(nroFuncionario) ||
           this.modelo.textoVacio(anioIngreso) ){
            
            datosValidos = false;
            JOptionPane.showMessageDialog(this,"Debe completar todos los campos.", "Campos incompletos",0);     
        }
        
        if((datosValidos) && !this.modelo.esSoloLetrasYEspacios(nombre)){
            datosValidos = false;
            JOptionPane.showMessageDialog(this,"El nombre no puede contener números ni caracteres especiales.", "Eror de formato",0);
        }
        
         if(datosValidos){
            for (int i=0; i<celular.length() && datosValidos;i++){
                if (!Character.isDigit(celular.charAt(i))){
                    datosValidos=false;
                    JOptionPane.showMessageDialog(this, "El celular solo puede tener números.", "Error de formato",0);
                }
            }   
        }
        int nro = 0;
        int anio = 0;
            
        if (datosValidos){
            try{
                nro = Integer.parseInt(nroFuncionario);
                anio = Integer.parseInt(anioIngreso);

                if (anio <1950 || anio >2026){
                    datosValidos = false;
                    JOptionPane.showMessageDialog(this,"El año de ingreso debe estar entre 1950 y 2026","Año incorrecto",0);
                }
            } catch (NumberFormatException e){
                datosValidos = false;
                JOptionPane.showMessageDialog(this,"El numero de funcionario y año deben ser numeros enteros", "Error de formato",0);
            }
        }
            
        Funcionario seleccionado = (Funcionario) lstFuncionarios.getSelectedValue();
            
        if (datosValidos){
            if(seleccionado == null){
                if(this.modelo.NombreYaExisteEnSistema(nombre)){
                    JOptionPane.showMessageDialog(this,"Ya existe un usuario en el sistema registrado con el mismo nombre");
                }else{
                    Funcionario nuevo = new Funcionario (nombre, celular, nro, anio);
                    this.modelo.agregarFuncionario(nuevo);
                    JOptionPane.showMessageDialog(this,"Funcionario registrado con éxito", "Registro exitoso", 1);
                    this.limpiarCampos();
            }
            }else{
                seleccionado.setNombre(nombre);
                seleccionado.setCelular(celular);
                seleccionado.setNroFuncionario(nro);
                seleccionado.setAnioIngreso(anio);

                //this.modelo.agregarFuncionario(null);
                JOptionPane.showMessageDialog(this, "Funcionario modificado con éxito.");
                this.limpiarCampos();
                lstFuncionarios.clearSelection();
            } 
        }
        
    }//GEN-LAST:event_BtnAgregarFuncionarioActionPerformed

    private void lstFuncionariosValueChanged(javax.swing.event.ListSelectionEvent evt){
        if(!evt.getValueIsAdjusting()){
            Funcionario seleccionado = (Funcionario) lstFuncionarios.getSelectedValue();
            if (seleccionado != null){
                txtNombreF.setText(seleccionado.getNombre());
                txtCelularF.setText(seleccionado.getCelular());
                txtNumeroF.setText(String.valueOf(seleccionado.getNroFuncionario()));
                txtAnioIngresoF.setText(String.valueOf(seleccionado.getAnioIngreso()));
                
                //txtNumeroF.setEditable(false); La letra no especifica q no se pueda modificar el nro Funcionario
                BtnAgregarFuncionario.setText("Modificar");
            }
        }
    }
    
    private void limpiarCampos(){
        txtNombreF.setText("");
        txtCelularF.setText("");
        txtNumeroF.setText("");
        txtAnioIngresoF.setText("");
        BtnAgregarFuncionario.setText("Agregar");
        txtNumeroF.setEditable(true);
        
        txtNombreF.requestFocus();
        
    }
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();    }//GEN-LAST:event_btnSalirActionPerformed

    private void lstFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstFuncionariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lstFuncionariosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarFuncionario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstFuncionarios;
    private javax.swing.JTextField txtAnioIngresoF;
    private javax.swing.JTextField txtCelularF;
    private javax.swing.JLabel txtMensaje;
    private javax.swing.JTextField txtNombreF;
    private javax.swing.JTextField txtNumeroF;
    // End of variables declaration//GEN-END:variables
}
