package interfaz;
import dominio.Sistema;
import dominio.ArchivoLog;

/*
 * Trabajo realizado por 
 * (333503) Daniel López
 * (372277) Lautaro Moreno
 */

public class DatosTarifas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DatosTarifas.class.getName());
    
    private Sistema modelo;

    /**
     * Creates new form TarifasPorZona
     */
    public DatosTarifas(Sistema modelo) {
        this.modelo = modelo;
        initComponents();
        
        buttonGroup1.add(rbtnAumentar);
        buttonGroup1.add(rbtnDisminuir);
        rbtnAumentar.setSelected(true);
        
        cargarTablaTarifas();

    }
    
    private void cargarTablaTarifas(){
        String [] columnas = {"Zonas", "Categoria 1", "Categoria 2", "Categoria 3", "Categoria 4"};
        
        javax.swing.table.DefaultTableModel modeloTabla = new javax.swing.table.DefaultTableModel(columnas,0){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        java.util.ArrayList<dominio.Tarifa> listaDeTarifas = this.modelo.getTarifas();
        
        for(int i=0; i<listaDeTarifas.size(); i++){
            dominio.Tarifa t = listaDeTarifas.get(i);
            Object[] fila = { t.getZona(),t.getPrecioCat1(),t.getPrecioCat2(),t.getPrecioCat3(),t.getPrecioCat4()};
            
            modeloTabla.addRow(fila);
        }
        tblMain.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblModTarifa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtModTarifa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rbtnAumentar = new javax.swing.JRadioButton();
        rbtnDisminuir = new javax.swing.JRadioButton();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        lblModTarifa.setText("Modificar Tarifa");
        jPanel1.add(lblModTarifa);
        lblModTarifa.setBounds(23, 434, 84, 16);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setText("Tarifas por zona");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 40, 186, 32);

        txtModTarifa.addActionListener(this::txtModTarifaActionPerformed);
        jPanel1.add(txtModTarifa);
        txtModTarifa.setBounds(122, 429, 88, 26);

        jLabel7.setText("%");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(210, 430, 10, 16);

        rbtnAumentar.setText("Aumentar");
        rbtnAumentar.addActionListener(this::rbtnAumentarActionPerformed);
        jPanel1.add(rbtnAumentar);
        rbtnAumentar.setBounds(303, 432, 78, 21);

        rbtnDisminuir.setText("Disminuir");
        rbtnDisminuir.addActionListener(this::rbtnDisminuirActionPerformed);
        jPanel1.add(rbtnDisminuir);
        rbtnDisminuir.setBounds(426, 432, 76, 21);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);
        jPanel1.add(btnActualizar);
        btnActualizar.setBounds(290, 470, 100, 27);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(405, 472, 110, 27);

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblMain);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(55, 101, 460, 277);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 570, 536);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String textoPorcentaje = txtModTarifa.getText().trim();
        boolean ok = true;
        
        if(this.modelo.textoVacio(textoPorcentaje)) { 
            javax.swing.JOptionPane.showMessageDialog(this,"Debe ingresar un porcetnaje", "Campo Vacío", 0 );
            ok = false;
        }
        if (ok){
        
        try {
            int porcentaje = Integer.parseInt(textoPorcentaje);
            
            if(porcentaje <= 0){
            javax.swing.JOptionPane.showMessageDialog(this,"El porcentaje debe ser mayor a cero", "Valor inválido", 0 );
            ok = false;
            }
            if(ok){
            boolean esAumento = rbtnAumentar.isSelected();
            
            java.util.ArrayList<dominio.Tarifa> listaDeTarifas = this.modelo.getTarifas();
            for(int i =0 ; i<listaDeTarifas.size(); i++){
                dominio.Tarifa t = listaDeTarifas.get(i);
                
               t.actualizarTarifa(porcentaje, esAumento);
                
            }
            String operacion = esAumento? "Aumento" : "Disminución";
            ArchivoLog.registrar("Modificación de tarifas:" + operacion +  "del" + porcentaje + "%");
            
            this.modelo.marcarCambio();
            this.modelo.serializar();
            cargarTablaTarifas();
            
            txtModTarifa.setText("");
            javax.swing.JOptionPane.showMessageDialog(this,"Tarifas actualizadas con éxito", "Actualización exitosa", 1);
            }
        } catch (NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this,"El porcentaje debe ser un número válido","Error de formato",0);
            ok = false;
        }
        
            
    }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void rbtnDisminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDisminuirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDisminuirActionPerformed

    private void rbtnAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAumentarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAumentarActionPerformed

    private void txtModTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModTarifaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModTarifaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
this.dispose();    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblModTarifa;
    private javax.swing.JRadioButton rbtnAumentar;
    private javax.swing.JRadioButton rbtnDisminuir;
    private javax.swing.JTable tblMain;
    private javax.swing.JTextField txtModTarifa;
    // End of variables declaration//GEN-END:variables

}