package interfaz;
import java.util.Observer;
import java.util.Observable;
import dominio.Funcionario;
import dominio.Sistema;
import javax.swing.JOptionPane;

/**
 *
 * @author lautaromoreno
 */
public class ListarFuncionarios extends javax.swing.JFrame implements Observer{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListarFuncionarios.class.getName());

        private Sistema modelo;
        
    public ListarFuncionarios(Sistema modelo) {
        this.modelo = modelo;
        this.modelo.addObserver(this);
        initComponents();
        objetoAPantalla();
        
        lstFuncionarios.addListSelectionListener(e -> lstFuncionariosValueChanged(e));
    }
    
    private void objetoAPantalla(){
        java.util.ArrayList<Funcionario> lista = this.modelo.getFuncionarios();
        lista.sort((f1,f2) -> Integer.compare(f2.getNroFuncionario(),f1.getNroFuncionario()));
        lstFuncionarios.setListData(lista.toArray());
    }
    
    @Override
   public void update (Observable o, Object arg){
       objetoAPantalla();
   }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreF = new javax.swing.JTextField();
        txtCelularF = new javax.swing.JTextField();
        txtNumeroF = new javax.swing.JTextField();
        txtAnioIngresoF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFuncionarios = new javax.swing.JList();
        BtnAgregarFuncionario = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Lista de Funcionarios");

        jLabel2.setText("Nombre");

        jLabel3.setText("Celular");

        jLabel4.setText("Nro de Funcionario");

        jLabel5.setText("Año de Ingreso");

        txtNombreF.addActionListener(this::txtNombreFActionPerformed);

        jScrollPane1.setViewportView(lstFuncionarios);

        BtnAgregarFuncionario.setText("Agregar Funcionario");
        BtnAgregarFuncionario.addActionListener(this::BtnAgregarFuncionarioActionPerformed);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreF)
                                    .addComponent(txtCelularF)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(24, 24, 24)
                                .addComponent(txtNumeroF, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMensaje)
                                    .addComponent(jLabel5))
                                .addGap(46, 46, 46)
                                .addComponent(txtAnioIngresoF)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAgregarFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombreF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelularF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAnioIngresoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMensaje))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAgregarFuncionario)
                    .addComponent(btnSalir))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 637, 415);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreFActionPerformed

    private void BtnAgregarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarFuncionarioActionPerformed
        String nombre = txtNombreF.getText();
        String celular = txtCelularF.getText();
        String nroFuncionario = txtNumeroF.getText();
        String anioIngreso = txtAnioIngresoF.getText();
        
        boolean datosValidos = true;
        txtMensaje.setText("");
        
        if(this.modelo.textoVacio(nombre) ||
           this.modelo.textoVacio(celular) ||
           this.modelo.textoVacio(nroFuncionario) ||
            this.modelo.textoVacio(anioIngreso) ){
            
            datosValidos = false;
            JOptionPane.showMessageDialog(this,"Debe completar todos los campos.", "Campos incompletos",0);
            
        }
        if((datosValidos) && !this.modelo.esSoloLetrasYEspacios(nombre)){
            datosValidos = false;
            JOptionPane.showMessageDialog(this,"El nombre no puede contener números ni caracteres especiales.", "Eror de formato",0);
        }
        
         if(datosValidos){
            for (int i=0; i<celular.length() && datosValidos;i++){
                if (!Character.isDigit(celular.charAt(i))){
                    datosValidos=false;
                    JOptionPane.showMessageDialog(this, "El celular solo puede tener números.", "Error de formato",0);

                    
                }
                
            }
            
        }        
        int nro = 0;
        int anio = 0;
            

            if (datosValidos){
                try{
                    nro = Integer.parseInt(nroFuncionario);
                    anio = Integer.parseInt(anioIngreso);
                    
                    if (anio <1900 || anio >2026){
                        datosValidos = false;
                         JOptionPane.showMessageDialog(this,"El año de ingreso no es válido","Año incorrecto",0);
                    }
                } catch (NumberFormatException e){
                    datosValidos = false;
                    JOptionPane.showMessageDialog(this,"El numero de funcionario y año deben ser numeros enteros", "Error de formato",0);
                }
                     
            }
            
            if (datosValidos){
               Funcionario nuevo = new Funcionario (nombre, celular, nro, anio);
                this.modelo.agregarFuncionario(nuevo);
                
                JOptionPane.showMessageDialog(this,"Funcionario registrado con éxito", "Registro exitoso", 1);
                this.limpiarCampos();
                
                
                
            }
            
        

    }//GEN-LAST:event_BtnAgregarFuncionarioActionPerformed

    private void lstFuncionariosValueChanged(javax.swing.event.ListSelectionEvent evt){
        if(!evt.getValueIsAdjusting()){
            Funcionario seleccionado = (Funcionario) lstFuncionarios.getSelectedValue();
            if (seleccionado != null){
                txtNombreF.setText(seleccionado.getNombre());
                txtCelularF.setText(seleccionado.getCelular());
                txtNumeroF.setText(String.valueOf(seleccionado.getNroFuncionario()));
                txtAnioIngresoF.setText(String.valueOf(seleccionado.getAnioIngreso()));
                
                txtNumeroF.setEditable(false);
                BtnAgregarFuncionario.setText("Guardar Cambios");
            }
        }
    }
    
    private void limpiarCampos(){
        txtNombreF.setText("");
        txtCelularF.setText("");
        txtNumeroF.setText("");
        txtAnioIngresoF.setText("");
        BtnAgregarFuncionario.setText("Nuevo Funcionario");
        txtNumeroF.setEditable(true);
        
        txtNombreF.requestFocus();
        
    }
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
this.dispose();    }//GEN-LAST:event_btnSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarFuncionario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstFuncionarios;
    private javax.swing.JTextField txtAnioIngresoF;
    private javax.swing.JTextField txtCelularF;
    private javax.swing.JLabel txtMensaje;
    private javax.swing.JTextField txtNombreF;
    private javax.swing.JTextField txtNumeroF;
    // End of variables declaration//GEN-END:variables
}
