package interfaz;
import dominio.Sistema;
/**
* Trabajo realizado por 
 * (333503) Daniel López
 * (372277) Lautaro Moreno
 */
public class NuevoCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NuevoCliente.class.getName());
    
    private Sistema modelo;
    

    /**
     * Creates new form NuevoCliente
     */
    public NuevoCliente(Sistema modelo) {
        this.modelo = modelo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        bnbSalir = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        txtMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setText("Agregar nuevo cliente");
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(30, 20, 320, 40);

        lblNombre.setText("Nombre:");
        jPanel1.add(lblNombre);
        lblNombre.setBounds(30, 90, 70, 16);
        jPanel1.add(txtNombre);
        txtNombre.setBounds(90, 90, 270, 26);

        lblCelular.setText("Celular:");
        jPanel1.add(lblCelular);
        lblCelular.setBounds(40, 150, 60, 16);

        lblEmail.setText("Email:");
        jPanel1.add(lblEmail);
        lblEmail.setBounds(50, 210, 37, 16);

        txtCelular.addActionListener(this::txtCelularActionPerformed);
        jPanel1.add(txtCelular);
        txtCelular.setBounds(90, 150, 270, 26);
        jPanel1.add(txtEmail);
        txtEmail.setBounds(90, 210, 270, 26);

        bnbSalir.setText("Salir");
        bnbSalir.addActionListener(this::bnbSalirActionPerformed);
        jPanel1.add(bnbSalir);
        bnbSalir.setBounds(290, 290, 76, 27);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);
        jPanel1.add(btnAgregar);
        btnAgregar.setBounds(200, 290, 79, 27);
        jPanel1.add(txtMensaje);
        txtMensaje.setBounds(60, 260, 270, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        setBounds(0, 0, 416, 355);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void bnbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_bnbSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        boolean datosValidos = true;
        txtMensaje.setText("");
        
        
        String nombre = txtNombre.getText(); //No debe contener número
        String celular = txtCelular.getText(); //Deben ser números
        String email = txtEmail.getText();// ToDo: Mejorar validación de Email
        
        //Valido datos contengan texto
        if(  (this.modelo.textoVacio(nombre)) ||
             (this.modelo.textoVacio(celular)) ||
             (this.modelo.textoVacio(email)) 
        ){
            datosValidos = false;
            txtMensaje.setText("Debe completar todos los campos.");
            
        }
        else if(!email.contains("@")){
            datosValidos = false;
            txtMensaje.setText("El email no es válido."); 
        }
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnbSalir;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtMensaje;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
