package interfaz;
import dominio.Sistema;

/**
* Trabajo realizado por 
 * (333503) Daniel López
 * (372277) Lautaro Moreno
 */
public class PaqueteRecepcion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaqueteRecepcion.class.getName());
    
    Sistema modelo;

    /**
     * Creates new form PaqueteRecepcion
     */
    public PaqueteRecepcion(Sistema modelo) {
        this.modelo = modelo;
        initComponents();
        objetoAPantalla();
    }
    
    public void objetoAPantalla(){
        lstEnvios.setListData(modelo.getEnviosOrdenadosDescendente().toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblEnvios = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEnvios = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Recepción");
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(130, 10, 160, 40);

        lblEnvios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnvios.setText("Envíos");
        jPanel1.add(lblEnvios);
        lblEnvios.setBounds(170, 70, 70, 16);

        lstEnvios.setModel(new javax.swing.AbstractListModel<Object>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstEnvios);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 90, 350, 110);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(30, 270, 350, 110);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Paquetes del envío seleccionado");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 250, 240, 16);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(269, 400, 110, 27);

        btnConfirmar.setText("Confirmar");
        jPanel1.add(btnConfirmar);
        btnConfirmar.setBounds(150, 400, 100, 27);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 450);

        setBounds(0, 0, 416, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEnvios;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<Object> lstEnvios;
    // End of variables declaration//GEN-END:variables
}
