
package interfaz;
import dominio.Sistema;
import dominio.Paquete;
import dominio.Envio;
import dominio.Funcionario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;

/*
 * Trabajo realizado por 
 * (333503) Daniel López
 * (372277) Lautaro Moreno
    
Duda: Es válido tener acá un Setter/Getter del arraylist auxiliar? Getter no hay, le pego direco al atributo.
 */
public class PaqueteEnvio extends javax.swing.JFrame implements Observer {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaqueteEnvio.class.getName());
    
    Sistema modelo;
    ArrayList<Paquete> paquetesPendientesEnZona = new ArrayList<Paquete>();
    DefaultListModel<Object> paqueteParaEnvio = new DefaultListModel<>();
    
    public PaqueteEnvio(Sistema modelo) {
        this.modelo = modelo;
        this.modelo.addObserver(this);
        initComponents();
        objetoAPantalla();
        this.setLocationRelativeTo(null);
    }
    
    private void objetoAPantalla(){
        
        int paqueteNro = Envio.getProximoId();
        lblTitulo.setText("Nuevo envío (número " + paqueteNro + ")");
        lstFuncionario.setListData(modelo.getFuncionarios().toArray());
        lstEnvio.setModel(paqueteParaEnvio);
        this.mostrarElementos(false);
        
    }
    
    private void mostrarElementos(boolean mostrar){
        lblPendientes.setVisible(mostrar);
        lblEnvio.setVisible(mostrar);
        jScrollPane2.setVisible(mostrar);
        lstEnvio.setVisible(mostrar);
        jScrollPane3.setVisible(mostrar);
        lstPendientes.setVisible(mostrar);
        btnAgregar.setVisible(mostrar);
        btnQuitar.setVisible(mostrar);
        lblCantPaquetes.setVisible(mostrar);
        lblPesoKgs.setVisible(mostrar);
        lblPesoGrs.setVisible(mostrar);
        lblMonto.setVisible(mostrar);
        btnConfirmar.setVisible(mostrar);
    }

    @Override
    public void update(Observable o, Object arg) {
        objetoAPantalla();
    }
    
    private void actualizarValoresEnvio(){
        int cantPaquetesEnvio = paqueteParaEnvio.size();
        double pesoKilos = this.modelo.pesoDePaquetes(paqueteParaEnvio, true);
        double pesoGramos = this.modelo.pesoDePaquetes(paqueteParaEnvio, false);
        int precio = this.modelo.precioDePaquetes(paqueteParaEnvio);
        
        lblCantPaquetes.setText("Paquetes en Envío: " + cantPaquetesEnvio);
        lblPesoKgs.setText("Peso total (Kgs): " + pesoKilos);
        lblPesoGrs.setText("Peso total (Grs): " + pesoGramos);
        lblMonto.setText("Monto Total: " + precio);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFuncionario = new javax.swing.JList<>();
        lblFuncionario = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblZona = new javax.swing.JLabel();
        cmbZona = new javax.swing.JComboBox<>();
        btnCargarPendientes = new javax.swing.JButton();
        lblPendientes = new javax.swing.JLabel();
        lblEnvio = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEnvio = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstPendientes = new javax.swing.JList<>();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        lblCantPaquetes = new javax.swing.JLabel();
        lblPesoKgs = new javax.swing.JLabel();
        lblPesoGrs = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Envío");
        getContentPane().setLayout(null);

        panel.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Nuevo Envío (núm x)");
        panel.add(lblTitulo);
        lblTitulo.setBounds(270, 20, 290, 50);

        lstFuncionario.setModel(new javax.swing.AbstractListModel<Object>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstFuncionario);

        panel.add(jScrollPane1);
        jScrollPane1.setBounds(120, 80, 210, 120);

        lblFuncionario.setText("Funcionario:");
        panel.add(lblFuncionario);
        lblFuncionario.setBounds(30, 80, 80, 16);

        lblFecha.setText("Fecha (dd/mm/yyyy):");
        panel.add(lblFecha);
        lblFecha.setBounds(390, 90, 130, 16);

        txtFecha.addActionListener(this::txtFechaActionPerformed);
        panel.add(txtFecha);
        txtFecha.setBounds(520, 90, 150, 26);

        lblZona.setText("Zona:");
        panel.add(lblZona);
        lblZona.setBounds(390, 140, 70, 16);

        cmbZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NORTE", "SUR", "ESTE", "OESTE" }));
        cmbZona.addActionListener(this::cmbZonaActionPerformed);
        panel.add(cmbZona);
        cmbZona.setBounds(460, 140, 210, 26);

        btnCargarPendientes.setText("Cargar pendientes");
        btnCargarPendientes.addActionListener(this::btnCargarPendientesActionPerformed);
        panel.add(btnCargarPendientes);
        btnCargarPendientes.setBounds(530, 180, 140, 30);

        lblPendientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPendientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPendientes.setText("Paquetes Pendientes");
        panel.add(lblPendientes);
        lblPendientes.setBounds(70, 240, 190, 30);

        lblEnvio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEnvio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnvio.setText("Paquetes en Envío");
        panel.add(lblEnvio);
        lblEnvio.setBounds(480, 240, 210, 30);

        lstEnvio.setModel(new javax.swing.AbstractListModel<Object>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstEnvio);

        panel.add(jScrollPane2);
        jScrollPane2.setBounds(440, 280, 280, 170);

        lstPendientes.setModel(new javax.swing.AbstractListModel<Object>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstPendientes);

        panel.add(jScrollPane3);
        jScrollPane3.setBounds(30, 280, 280, 170);

        btnAgregar.setText("Agregar →");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);
        panel.add(btnAgregar);
        btnAgregar.setBounds(320, 310, 110, 27);

        btnQuitar.setText("← Quitar");
        btnQuitar.addActionListener(this::btnQuitarActionPerformed);
        panel.add(btnQuitar);
        btnQuitar.setBounds(320, 360, 110, 27);

        lblCantPaquetes.setText("Paquetes en Envío:");
        panel.add(lblCantPaquetes);
        lblCantPaquetes.setBounds(440, 460, 280, 16);

        lblPesoKgs.setText("Peso total (Kgs):");
        panel.add(lblPesoKgs);
        lblPesoKgs.setBounds(440, 480, 280, 16);

        lblPesoGrs.setText("Peso total (Grs): ");
        panel.add(lblPesoGrs);
        lblPesoGrs.setBounds(440, 500, 280, 16);

        lblMonto.setText("Monto Total:  ");
        panel.add(lblMonto);
        lblMonto.setBounds(440, 520, 280, 16);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        panel.add(btnCancelar);
        btnCancelar.setBounds(610, 560, 100, 27);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(this::btnConfirmarActionPerformed);
        panel.add(btnConfirmar);
        btnConfirmar.setBounds(500, 560, 100, 27);

        getContentPane().add(panel);
        panel.setBounds(0, 0, 790, 630);

        setBounds(0, 0, 811, 641);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        Paquete paquete = (Paquete) lstPendientes.getSelectedValue();
        String zona = (String) cmbZona.getSelectedItem();   
        if (paquete != null) {
            paqueteParaEnvio.addElement(paquete);
            
            this.paquetesPendientesEnZona.remove(paquete);
            lstPendientes.setListData(this.paquetesPendientesEnZona.toArray());
            this.actualizarValoresEnvio();
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione el paquete que quiere agregar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbZonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbZonaActionPerformed

    private void btnCargarPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarPendientesActionPerformed
        
        paqueteParaEnvio.clear();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false);
        lstEnvio.getModel();
        String zona = (String) cmbZona.getSelectedItem();
        //lstFuncionario.setEditable(false);
        //txtFecha.setEditable(false);
        //cmbZona.setEditable(false);
        
        /*try{   
            Funcionario funcionario = (Funcionario) lstFuncionario.getSelectedValue();
            Date fecha = sdf.parse(txtFecha.getText().trim());
            String zona = (String) cmbZona.getSelectedItem();
            
            if(funcionario == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un funcionario", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                
                this.paquetesPendientesEnZona = this.modelo.getPaquetesPendientesPorZona(zona);
                if(paquetesPendientesEnZona.size() == 0){
                    this.mostrarElementos(false);
                    JOptionPane.showMessageDialog(this, "No existen paquetes para la zona " + zona, "Información", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    lstPendientes.setListData(paquetesPendientesEnZona.toArray());     
                    this.mostrarElementos(true);
                }
            }       
        }catch(ParseException e){
            JOptionPane.showMessageDialog(this, "Fecha inválida.", "Error", JOptionPane.ERROR_MESSAGE);
        }*/
        this.paquetesPendientesEnZona = this.modelo.getPaquetesPendientesPorZona(zona);
        if(paquetesPendientesEnZona.size() == 0){
                    this.mostrarElementos(false);
                    JOptionPane.showMessageDialog(this, "No existen paquetes para la zona " + zona, "Información", JOptionPane.INFORMATION_MESSAGE);
                }
        else{
            lstPendientes.setListData(paquetesPendientesEnZona.toArray());     
            this.mostrarElementos(true);
        }
    }//GEN-LAST:event_btnCargarPendientesActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false);
        Funcionario func = (Funcionario) lstFuncionario.getSelectedValue();
        if(func != null){
            try{
                Date fecha = sdf.parse(txtFecha.getText().trim());
                
                if (fecha.before(sdf.parse("01/01/2020")) || fecha.after(sdf.parse("31/12/2026"))) {
                    throw new IllegalArgumentException(); //Consulto a IA cual es la mejor excepción para este caso, en lugar de usar excepción genérica Exception().
                }

                String zona = (String) cmbZona.getSelectedItem(); 
                ArrayList<Paquete> paquetes = new ArrayList<>();

                for (int i = 0; i < paqueteParaEnvio.getSize(); i++) {
                    Paquete p = (Paquete)paqueteParaEnvio.getElementAt(i);
                    p.setEstado("Enviado");
                    paquetes.add(p);
                }

                Envio nuevoEnvio = new Envio(fecha, zona, func, paquetes); 
                this.modelo.agregarEnvios(nuevoEnvio);

                paqueteParaEnvio.clear();
                txtFecha.setText("");
                JOptionPane.showMessageDialog(this, "El envío fue creado correctamente.", "Envío creado", JOptionPane.INFORMATION_MESSAGE);   

            } catch(ParseException e){
                JOptionPane.showMessageDialog(this, "Fecha inválida.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            catch (IllegalArgumentException e){
                JOptionPane.showMessageDialog(this, "Fecha debe estar comprendida entre 01/01/2020 y 31/12/2026", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione un funcionario.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        
        Paquete paquete = (Paquete) lstEnvio.getSelectedValue();
        
        if (paquete != null) {
            this.paquetesPendientesEnZona.add(paquete);
            this.paqueteParaEnvio.removeElement(paquete);
            lstPendientes.setListData(this.paquetesPendientesEnZona.toArray());
            this.actualizarValoresEnvio();
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione el paquete que quiere quitar del envío.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargarPendientes;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JComboBox<String> cmbZona;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCantPaquetes;
    private javax.swing.JLabel lblEnvio;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblPendientes;
    private javax.swing.JLabel lblPesoGrs;
    private javax.swing.JLabel lblPesoKgs;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblZona;
    private javax.swing.JList<Object> lstEnvio;
    private javax.swing.JList<Object> lstFuncionario;
    private javax.swing.JList<Object> lstPendientes;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
