
package interfaz;
import dominio.Sistema;
import dominio.Paquete;
import dominio.Envio;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Trabajo realizado por 
 * (333503) Daniel López
 * (372277) Lautaro Moreno
    
Duda: Es válido tener acá un Setter/Getter del arraylist auxiliar? Getter no hay, le pego direco al atributo.
 */
public class PaqueteEnvio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaqueteEnvio.class.getName());
    
    Sistema modelo;
    ArrayList<Paquete> auxPaqueteEnvio = new ArrayList<Paquete>();

    /**
     * Creates new form PaqueteEnvio
     */
    public PaqueteEnvio(Sistema modelo) {
        this.modelo = modelo;
        initComponents();
        objetoAPantalla();
    }
    
    private void objetoAPantalla(){
        
        int paqueteNro = modelo.getEnvios().size() + 1;
        lblTitulo.setText("Nuevo envío (número " + paqueteNro + ")");
        lstClientes.setListData(modelo.getClientes().toArray());
        cmbZona.addItem("NORTE");
        cmbZona.addItem("SUR");
        cmbZona.addItem("ESTE");
        cmbZona.addItem("OESTE");
        this.mostrarElementos(false);
    }
    
    private void mostrarElementos(boolean mostrar){
        lblPendientes.setVisible(mostrar);
        lblEnvio.setVisible(mostrar);
        jScrollPane2.setVisible(mostrar);
        lstEnvio.setVisible(mostrar);
        jScrollPane3.setVisible(mostrar);
        lstPendientes.setVisible(mostrar);
        btnAgregar.setVisible(mostrar);
        btnQuitar.setVisible(mostrar);
        lblCantPaquetes.setVisible(mostrar);
        lblPesoKgs.setVisible(mostrar);
        lblPesoGrs.setVisible(mostrar);
        lblMonto.setVisible(mostrar);
        btnConfirmar.setVisible(mostrar);
    }
    
    public void quitarPaquete(Paquete paquete) {
        this.auxPaqueteEnvio.remove(paquete);
    }
    
    public void agregarPaquete(Paquete paquete) {
        this.auxPaqueteEnvio.add(paquete);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstClientes = new javax.swing.JList<>();
        lblCliente = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblZona = new javax.swing.JLabel();
        cmbZona = new javax.swing.JComboBox<>();
        btnCargarPendientes = new javax.swing.JButton();
        lblPendientes = new javax.swing.JLabel();
        lblEnvio = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEnvio = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstPendientes = new javax.swing.JList<>();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        lblCantPaquetes = new javax.swing.JLabel();
        lblPesoKgs = new javax.swing.JLabel();
        lblPesoGrs = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        panel.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Nuevo Envío (núm x)");
        panel.add(lblTitulo);
        lblTitulo.setBounds(270, 20, 290, 50);

        lstClientes.setModel(new javax.swing.AbstractListModel<Object>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstClientes);

        panel.add(jScrollPane1);
        jScrollPane1.setBounds(100, 80, 210, 80);

        lblCliente.setText("Cliente:");
        panel.add(lblCliente);
        lblCliente.setBounds(30, 80, 70, 16);

        lblFecha.setText("Fecha:");
        panel.add(lblFecha);
        lblFecha.setBounds(30, 180, 70, 16);
        panel.add(txtFecha);
        txtFecha.setBounds(100, 180, 210, 26);

        lblZona.setText("Zona:");
        panel.add(lblZona);
        lblZona.setBounds(30, 230, 70, 16);

        cmbZona.addActionListener(this::cmbZonaActionPerformed);
        panel.add(cmbZona);
        cmbZona.setBounds(100, 230, 210, 26);

        btnCargarPendientes.setText("Cargar pendientes para esta zona");
        btnCargarPendientes.addActionListener(this::btnCargarPendientesActionPerformed);
        panel.add(btnCargarPendientes);
        btnCargarPendientes.setBounds(30, 280, 750, 40);

        lblPendientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPendientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPendientes.setText("Paquetes Pendientes");
        panel.add(lblPendientes);
        lblPendientes.setBounds(100, 330, 190, 30);

        lblEnvio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEnvio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnvio.setText("Paquetes en Envío");
        panel.add(lblEnvio);
        lblEnvio.setBounds(530, 330, 210, 30);

        lstEnvio.setModel(new javax.swing.AbstractListModel<Object>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstEnvio);

        panel.add(jScrollPane2);
        jScrollPane2.setBounds(490, 370, 280, 170);

        lstPendientes.setModel(new javax.swing.AbstractListModel<Object>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstPendientes);

        panel.add(jScrollPane3);
        jScrollPane3.setBounds(50, 370, 280, 170);

        btnAgregar.setText("Agregar →");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);
        panel.add(btnAgregar);
        btnAgregar.setBounds(360, 400, 110, 27);

        btnQuitar.setText("←Quitar");
        panel.add(btnQuitar);
        btnQuitar.setBounds(360, 450, 110, 27);

        lblCantPaquetes.setText("Paquetes en Envío:");
        panel.add(lblCantPaquetes);
        lblCantPaquetes.setBounds(500, 550, 140, 16);

        lblPesoKgs.setText("Peso total (Kgs):");
        panel.add(lblPesoKgs);
        lblPesoKgs.setBounds(500, 570, 100, 16);

        lblPesoGrs.setText("Peso total (Grs):");
        panel.add(lblPesoGrs);
        lblPesoGrs.setBounds(500, 590, 100, 16);

        lblMonto.setText("Monto Total: ");
        panel.add(lblMonto);
        lblMonto.setBounds(500, 610, 80, 16);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        panel.add(btnCancelar);
        btnCancelar.setBounds(680, 660, 90, 27);

        btnConfirmar.setText("Confirmar");
        panel.add(btnConfirmar);
        btnConfirmar.setBounds(580, 660, 90, 27);

        getContentPane().add(panel);
        panel.setBounds(0, 0, 820, 740);

        setBounds(0, 0, 832, 742);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbZonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbZonaActionPerformed

    private void btnCargarPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarPendientesActionPerformed
        String zona = (String) cmbZona.getSelectedItem();
        ArrayList<Paquete> paquetesPendientesEnZona = this.modelo.getPaquetesPendientesPorZona(zona);
        
        if(paquetesPendientesEnZona.size() == 0){
            this.mostrarElementos(false);
            JOptionPane.showMessageDialog(this, "No existen paquetes para la zona " + zona, "Atención", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            lstPendientes.setListData(paquetesPendientesEnZona.toArray());     
            this.mostrarElementos(true);
        }
    }//GEN-LAST:event_btnCargarPendientesActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargarPendientes;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JComboBox<String> cmbZona;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCantPaquetes;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEnvio;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblPendientes;
    private javax.swing.JLabel lblPesoGrs;
    private javax.swing.JLabel lblPesoKgs;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblZona;
    private javax.swing.JList<Object> lstClientes;
    private javax.swing.JList<Object> lstEnvio;
    private javax.swing.JList<Object> lstPendientes;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
