package interfaz;
import dominio.Cliente;
import dominio.Sistema;
import dominio.Paquete;
import java.util.Observer;
import java.util.Observable;

/**
 *
 * @author lautaromoreno
 */
public class ReportesConsultaPorCliente extends javax.swing.JFrame implements Observer {
    

    private Sistema modelo;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportesConsultaPorCliente.class.getName());
    


    public ReportesConsultaPorCliente(Sistema modelo) {
        this.modelo= modelo;
        this.modelo.addObserver(this);

        initComponents();
        
        lstClientes.addListSelectionListener(this::lstClientesValueChanged);
        cargarLista();
        
        //this.setSize(400,500);
        this.setLocationRelativeTo(null);
    }
    private void cargarLista(){
        lstClientes.removeListSelectionListener(this::lstClientesValueChanged);
        lstClientes.setListData(this.modelo.getClientes().toArray());
        lstClientes.addListSelectionListener(this::lstClientesValueChanged);
    }
    @Override
    public void update(java.util.Observable o,Object arg){
        cargarLista();
    }
    
    private void lstClientesValueChanged(javax.swing.event.ListSelectionEvent evt){
        if(!evt.getValueIsAdjusting()){
            Cliente seleccionado =  (Cliente) lstClientes.getSelectedValue();
            
            int pendientes = 0;
            int enviados = 0;
            int recibidos = 0;
            
            if(seleccionado != null){
                pendientes = this.modelo.contarPaquetesPorClienteYEstado(seleccionado, "Pendiente");
                enviados = this.modelo.contarPaquetesPorClienteYEstado(seleccionado, "Enviado");
                recibidos =  this.modelo.contarPaquetesPorClienteYEstado(seleccionado, "Recibido");   
            }
                
                lblPendientes.setText(String.valueOf("Pendientes:" + pendientes));
                lblEnviados.setText(String.valueOf("Enviados: " + enviados));
                lblRecibidos.setText(String.valueOf("Recibidos: " + recibidos));
            }
                
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstClientes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        lblPendientes = new javax.swing.JLabel();
        lblEnviados = new javax.swing.JLabel();
        lblRecibidos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta por Cliente");
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(lstClientes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 140, 130);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Consulte paquetes de un cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 310, 20);

        lblPendientes.setText("Pendientes: 0");
        getContentPane().add(lblPendientes);
        lblPendientes.setBounds(180, 60, 90, 17);

        lblEnviados.setText("Enviados:  0");
        getContentPane().add(lblEnviados);
        lblEnviados.setBounds(180, 100, 100, 17);

        lblRecibidos.setText("Recibidos:   0");
        getContentPane().add(lblRecibidos);
        lblRecibidos.setBounds(180, 140, 120, 17);

        jButton1.setText("Cancelar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 220, 90, 23);

        setBounds(0, 0, 361, 288);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnviados;
    private javax.swing.JLabel lblPendientes;
    private javax.swing.JLabel lblRecibidos;
    private javax.swing.JList<Object> lstClientes;
    // End of variables declaration//GEN-END:variables
}
