
package interfaz;
import dominio.Sistema;

/**
 *
 * @author lautaromoreno
 */
public class ReportesPaquetesPorEstado extends javax.swing.JFrame {
    

    private Sistema modelo;
    
    public ReportesPaquetesPorEstado(Sistema unModelo) {
        this.modelo = unModelo;
        initComponents();
        
        if(this.modelo != null){
        cargarGrilla();
        }
        
        this.setSize (500,400);
        this.setPreferredSize(new java.awt.Dimension(500,400));
        this.setLocationRelativeTo(null);
    }
    
    private void cargarGrilla(){
        String[] columnas = {"","Pendiente","Enviado","Recibido","Total"};
        
        javax.swing.table.DefaultTableModel TablaReporte = new javax.swing.table.DefaultTableModel(columnas,0);
                
                String[] zonas = {"NORTE", "OESTE", "SUR", "ESTE"};
                
                for (int i = 0; i<zonas.length;i++){
                    String zonaActual = zonas[i];
                
                int pendientes = this.modelo.contarPaquetesPorZonaYEstado(zonaActual,"Pendiente");
                int enviados = this.modelo.contarPaquetesPorZonaYEstado(zonaActual,"Enviado");
                int recibidos = this.modelo.contarPaquetesPorZonaYEstado(zonaActual,"Recibido");
                int totalZona = pendientes + enviados + recibidos;
                
                String nombreZonaOk = zonaActual.substring(0,1) + zonaActual.substring(1).toLowerCase();
                
                Object[] fila = {
                nombreZonaOk,
                pendientes,
                enviados,
                recibidos,
                totalZona
                };
                
                TablaReporte.addRow(fila);
                }
                this.tblReporte.setModel(TablaReporte);
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReporte);

        jButton1.setText("Salir");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReporte;
    // End of variables declaration//GEN-END:variables
}
