package interfaz;
import dominio.Sistema;
import dominio.Paquete;
import dominio.Cliente;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;

/**
* Trabajo realizado por 
 * (333503) Daniel López
 * (372277) Lautaro Moreno
 */
public class ReportesPaquetesPorEstado extends javax.swing.JFrame implements Observer {
    

    private Sistema modelo;
    
    public ReportesPaquetesPorEstado(Sistema unModelo) {
        this.modelo = unModelo;
        this.modelo.addObserver(this);
        initComponents();
        
        if(this.modelo != null){
            cargarGrilla();
            //configurarMapaUruguay();
        }
        
       // this.setSize (800,850);
        this.setPreferredSize(new java.awt.Dimension(800,850));
        this.setLocationRelativeTo(null);
        
        this.addWindowFocusListener(new java.awt.event.WindowAdapter (){
            @Override
            public void windowActivated (java.awt.event.WindowEvent e){
                actualizarDatosReporte();
            }
            
        });
    }
    
    @Override 
    public void update(Observable o, Object arg){
        actualizarDatosReporte();
    }
    
    private void cargarGrilla(){
        String[] columnas = {"","Pendiente","Enviado","Recibido","Total"};
        
        javax.swing.table.DefaultTableModel TablaReporte = new javax.swing.table.DefaultTableModel(columnas,0){

        @Override
        public boolean isCellEditable (int row, int column){
            boolean no = false;
                return no;
            }
        };

        String[] zonas = {"Norte", "Oeste", "Sur", "Este"};

        for(int i = 0; i<zonas.length;i++){
            String zonaActual = zonas[i];

        int pendientes = this.modelo.contarPaquetesPorZonaYEstado(zonaActual,"Pendiente");
        int enviados = this.modelo.contarPaquetesPorZonaYEstado(zonaActual,"Enviado");
        int recibidos = this.modelo.contarPaquetesPorZonaYEstado(zonaActual,"Recibido");
        int totalZona = pendientes + enviados + recibidos;

        String nombreZonaOk = zonaActual.substring(0,1) + zonaActual.substring(1).toLowerCase();

        Object[] fila = {
            nombreZonaOk,
            pendientes,
            enviados,
            recibidos,
            totalZona
        };

        TablaReporte.addRow(fila);
        }

        this.tblReporte.setModel(TablaReporte);

        this.tblReporte.setBackground(java.awt.Color.BLACK);
        this.tblReporte.setForeground(java.awt.Color.WHITE);

        this.tblReporte.setGridColor(new java.awt.Color(60,60,60));
        this.tblReporte.setShowGrid(true);
        this.tblReporte.setRowHeight(25);
    }
       
    public void actualizarDatosReporte(){
        if (this.modelo != null){
            cargarGrilla();
            //this.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelMapa = new javax.swing.JPanel();
        lblSur = new javax.swing.JLabel();
        lblNorte = new javax.swing.JLabel();
        lblEste = new javax.swing.JLabel();
        lblOeste = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paquetes por Estado");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Paquetes por Estado");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 20, 179, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(170, 0, 480, 50);

        panelMapa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSur.setBackground(new java.awt.Color(255, 255, 0));
        lblSur.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblSur.setText("Sur");
        lblSur.setOpaque(true);
        lblSur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSurMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSurMouseExited(evt);
            }
        });
        panelMapa.add(lblSur, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        lblNorte.setBackground(new java.awt.Color(255, 255, 0));
        lblNorte.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblNorte.setText("Norte");
        lblNorte.setOpaque(true);
        lblNorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNorteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNorteMouseExited(evt);
            }
        });
        panelMapa.add(lblNorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 100, 50));

        lblEste.setBackground(new java.awt.Color(255, 255, 0));
        lblEste.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblEste.setText("Este");
        lblEste.setOpaque(true);
        lblEste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEsteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEsteMouseExited(evt);
            }
        });
        panelMapa.add(lblEste, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 80, 40));

        lblOeste.setBackground(new java.awt.Color(255, 255, 0));
        lblOeste.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblOeste.setText("Oeste");
        lblOeste.setOpaque(true);
        lblOeste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOesteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOesteMouseExited(evt);
            }
        });
        panelMapa.add(lblOeste, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atl_ruteroUY_nuevoG.jpg"))); // NOI18N
        panelMapa.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 480));

        getContentPane().add(panelMapa);
        panelMapa.setBounds(-60, -20, 550, 530);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(610, 450, 0, 3);

        btnSalir.setText("Cancelar");
        btnSalir.addActionListener(this::btnSalirActionPerformed);
        getContentPane().add(btnSalir);
        btnSalir.setBounds(790, 480, 100, 30);

        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Zona", "Pendiente", "Enviado", "Recibido", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReporte.getTableHeader().setReorderingAllowed(false);
        tblReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReporteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReporte);
        if (tblReporte.getColumnModel().getColumnCount() > 0) {
            tblReporte.getColumnModel().getColumn(0).setResizable(false);
            tblReporte.getColumnModel().getColumn(1).setResizable(false);
            tblReporte.getColumnModel().getColumn(2).setResizable(false);
            tblReporte.getColumnModel().getColumn(3).setResizable(false);
            tblReporte.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(490, 60, 420, 170);

        setBounds(0, 0, 934, 571);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();       
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tblReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReporteMouseClicked
        // TODO add your handling code here:
        int fila = tblReporte.getSelectedRow();
        int columna = tblReporte.getSelectedColumn();
        ArrayList<Cliente> clientes = new ArrayList<>();
        ArrayList<String> departamentos = new ArrayList<>();
        String texto = "";
        
        if(columna != 0){ 
            String zona;
            String estado;

            if(fila == 0){
                zona = "NORTE";
            }else if(fila == 1){
                zona = "OESTE";
            }else if(fila == 2){
                zona = "SUR";
            }else{
                zona = "ESTE";
            }

            if(columna == 1){
                estado = "Pendiente";
            }else if(columna == 2){
                estado = "Enviado";
            }else if(columna == 3){
                estado = "Recibido";
            }else{
                estado = "Total";
            }
            
            
            for(int i=0; i<this.modelo.getPaquetes().size(); i++){
                Paquete p = this.modelo.getPaquetes().get(i);
                
                if(estado.equals("Total")){
                    if(p.getZona().equals(zona)){ 
                        if (!clientes.contains(p.getCliente())) {
                            clientes.add(p.getCliente());
                        }
                        if (!departamentos.contains(p.getDepartamentoEnvio())) {
                            departamentos.add(p.getDepartamentoEnvio());
                        }
                    }   
                }else{              
                    if((p.getZona().equals(zona)) && (p.getEstado().equals(estado))){ 
                        if (!clientes.contains(p.getCliente())) {
                            clientes.add(p.getCliente());
                        }
                        if (!departamentos.contains(p.getDepartamentoEnvio())) {
                            departamentos.add(p.getDepartamentoEnvio());
                        }
                    }
                }
                
            }
            
            for (int i = 0; i < departamentos.size(); i++) {
                texto += departamentos.get(i);

                if (i < departamentos.size() - 1) {
                    texto += ", ";
                }
            }
            
            int cantClientesDistintos = clientes.size();
            
            
           
            if(cantClientesDistintos==0){
                JOptionPane.showMessageDialog(this, "No hay paquetes registrados para esta zona y estado.");
            }else{
                JOptionPane.showMessageDialog(this, "Total de clientes distintos: " + cantClientesDistintos +"\n Enviado a dptos: " + texto);
            }

            
        }
        else{
            tblReporte.clearSelection();
        }
        
        

    }//GEN-LAST:event_tblReporteMouseClicked

    private void lblSurMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSurMouseEntered
        // TODO add your handling code here:
        lblSur.setBackground(new java.awt.Color(0,255,255));
        this.calcularValores("Sur");
    }//GEN-LAST:event_lblSurMouseEntered

    private void lblSurMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSurMouseExited
        // TODO add your handling code here:
        lblSur.setBackground(java.awt.Color.YELLOW);
    }//GEN-LAST:event_lblSurMouseExited

    private void lblEsteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEsteMouseEntered
        lblEste.setBackground(new java.awt.Color(0,255,255));
        this.calcularValores("Este");        // TODO add your handling code here:
    }//GEN-LAST:event_lblEsteMouseEntered

    private void lblOesteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOesteMouseEntered
        lblOeste.setBackground(new java.awt.Color(0,255,255));
        this.calcularValores("Oeste");          // TODO add your handling code here:
    }//GEN-LAST:event_lblOesteMouseEntered

    private void lblNorteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNorteMouseEntered
        lblNorte.setBackground(new java.awt.Color(0,255,255));
        this.calcularValores("Norte");          // TODO add your handling code here:
    }//GEN-LAST:event_lblNorteMouseEntered

    private void lblEsteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEsteMouseExited
        lblEste.setBackground(java.awt.Color.YELLOW);        // TODO add your handling code here:
    }//GEN-LAST:event_lblEsteMouseExited

    private void lblOesteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOesteMouseExited
        lblOeste.setBackground(java.awt.Color.YELLOW);        // TODO add your handling code here:
    }//GEN-LAST:event_lblOesteMouseExited

    private void lblNorteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNorteMouseExited
        lblNorte.setBackground(java.awt.Color.YELLOW);        // TODO add your handling code here:
    }//GEN-LAST:event_lblNorteMouseExited
    
    private void calcularValores(String zona){
        
        int paquetesPendientes = this.modelo.contarPaquetesPorZonaYEstado(zona, "Pendiente");
        int paquetesEnviados = this.modelo.contarPaquetesPorZonaYEstado(zona, "Enviado");
        int paquetesRecibidos = this.modelo.contarPaquetesPorZonaYEstado(zona, "Recibido");
        int totalZona = paquetesPendientes + paquetesEnviados + paquetesRecibidos;
        
        String mensajePopup = "Cantidad de paquetes en cada estado:\n\n"
                   + " Pendientes: " + paquetesPendientes 
                   + "\n" +" Enviados: " + paquetesEnviados + "\n" 
                   + " Recibidos: " +paquetesRecibidos+ "\n\n" 
                   + " Total Zona: " + totalZona;

        if(totalZona == 0){
            JOptionPane.showMessageDialog(ReportesPaquetesPorEstado.this, "No existen paquetes en esta zona" ,"Datos de la zona " + zona, JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(ReportesPaquetesPorEstado.this,mensajePopup,"Datos de la zona " + zona , JOptionPane.INFORMATION_MESSAGE);  
        }
        
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEste;
    private javax.swing.JLabel lblNorte;
    private javax.swing.JLabel lblOeste;
    private javax.swing.JLabel lblSur;
    private javax.swing.JPanel panelMapa;
    private javax.swing.JTable tblReporte;
    // End of variables declaration//GEN-END:variables
}
