
package interfaz;
import javax.swing.JOptionPane;
import dominio.ArchivoLog;
import dominio.Sistema;
import java.util.Observer;
import java.util.Observable;

/**
 *
 * @author lautaromoreno
 */
public class ReportesLogDeTransacciones extends javax.swing.JFrame implements Observer {
    private Sistema modelo;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportesLogDeTransacciones.class.getName());


    public ReportesLogDeTransacciones(Sistema modelo) {
        this.modelo = modelo;
        this.modelo.addObserver(this);
        initComponents();
        this.setSize(450,350);
        this.setLocationRelativeTo(null);
        txtLogs.setEditable(false);
        objetoAPantalla();
    }
    
    private void objetoAPantalla(){
        String contenido = ArchivoLog.obtenerContenido();
        txtLogs.setText(contenido);
    }
    
    @Override 
    public void update(Observable o, Object arg){
        objetoAPantalla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLogs = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnBorrarTodo = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Log de Transacciones");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        txtLogs.setEditable(false);
        txtLogs.setColumns(20);
        txtLogs.setRows(5);
        jScrollPane1.setViewportView(txtLogs);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(36, 47, 339, 169);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Log de Transacciones");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(98, 12, 190, 23);

        btnBorrarTodo.setText("Borrar todo");
        btnBorrarTodo.addActionListener(this::btnBorrarTodoActionPerformed);
        jPanel1.add(btnBorrarTodo);
        btnBorrarTodo.setBounds(189, 255, 95, 23);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);
        jPanel1.add(btnCerrar);
        btnCerrar.setBounds(296, 255, 72, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 390, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTodoActionPerformed
        int seleccion = JOptionPane.showConfirmDialog(this,"¿Está seguro que desea eliminar el historial de transacciones?\nEsta acción no se puede deshacer y se borraran los datos guardados","Confirmar",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        
        if (seleccion == JOptionPane.YES_OPTION){
            ArchivoLog.borrarContenido();
            objetoAPantalla();
            JOptionPane.showMessageDialog(this,"El archivo de log fue vaciado con éxito.","Historial Limpio", JOptionPane.INFORMATION_MESSAGE);
                    
        }
    }//GEN-LAST:event_btnBorrarTodoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
    this.dispose();        
    }//GEN-LAST:event_btnCerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarTodo;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtLogs;
    // End of variables declaration//GEN-END:variables
}
