package interfaz;
import dominio.Sistema;

public class TarifasPorZona extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TarifasPorZona.class.getName());
    
    private Sistema modelo;

    /**
     * Creates new form TarifasPorZona
     */
    public TarifasPorZona(Sistema modelo) {
        this.modelo = modelo;
        initComponents();
        
        buttonGroup1.add(rbtnAumentar);
        buttonGroup1.add(rbtnDisminuir);
        rbtnAumentar.setSelected(true);
        
        cargarTablaTarifas();

    }
    
    private void cargarTablaTarifas(){
        String [] columnas = {"Zonas", "Categoria 1", "Categoria 2", "Categoria 3", "Categoria 4"};
        
        javax.swing.table.DefaultTableModel modeloTabla = new javax.swing.table.DefaultTableModel(columnas,0){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        java.util.ArrayList<dominio.Tarifa> listaDeTarifas = this.modelo.getTarifas();
        
        for(int i=0; i<listaDeTarifas.size(); i++){
            dominio.Tarifa t = listaDeTarifas.get(i);
            Object[] fila = { t.getZona(),t.getPrecioCat1(),t.getPrecioCat2(),t.getPrecioCat3(),t.getPrecioCat4()};
            
            modeloTabla.addRow(fila);
        }
        jTable4.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblModTarifa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtModTarifa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rbtnAumentar = new javax.swing.JRadioButton();
        rbtnDisminuir = new javax.swing.JRadioButton();
        btnActualizar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblModTarifa.setText("Modificar Tarifa");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setText("Tarifas por zona");

        txtModTarifa.addActionListener(this::txtModTarifaActionPerformed);

        jLabel7.setText("%");

        rbtnAumentar.setText("Aumentar");
        rbtnAumentar.addActionListener(this::rbtnAumentarActionPerformed);

        rbtnDisminuir.setText("Disminuir");
        rbtnDisminuir.addActionListener(this::rbtnDisminuirActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblModTarifa)
                .addGap(15, 15, 15)
                .addComponent(txtModTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addGap(52, 52, 52)
                .addComponent(rbtnAumentar)
                .addGap(45, 45, 45)
                .addComponent(rbtnDisminuir)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(184, 184, 184))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnActualizar)
                        .addGap(38, 38, 38)
                        .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModTarifa)
                            .addComponent(txtModTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnAumentar)
                            .addComponent(rbtnDisminuir)
                            .addComponent(jLabel7))
                        .addGap(17, 17, 17)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnSalir))
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String textoPorcentaje = txtModTarifa.getText();
        boolean ok = true;
        
        if(this.modelo.textoVacio(textoPorcentaje)) { 
            javax.swing.JOptionPane.showMessageDialog(this,"Debe ingresar un porcetnaje", "Campo Vacío", 0 );
            ok = false;
        }
        if (ok){
        
        try {
            int porcentaje = Integer.parseInt(textoPorcentaje);
            
            if(porcentaje <= 0){
            javax.swing.JOptionPane.showMessageDialog(this,"El porcentaje debe ser mayor a cero", "Valor inválido", 0 );
            ok = false;
            }
            if(ok){
            boolean esAumento = rbtnAumentar.isSelected();
            
            
            java.util.ArrayList<dominio.Tarifa> listaDeTarifas = this.modelo.getTarifas();
            for(int i =0 ; i<listaDeTarifas.size(); i++){
                dominio.Tarifa t = listaDeTarifas.get(i);
                
               t.actualizarTarifa(porcentaje, esAumento);
                
            }
            
            cargarTablaTarifas();
            
            txtModTarifa.setText("");
            javax.swing.JOptionPane.showMessageDialog(this,"Tarifas actualizadas con éxito", "Actualización exitosa", 1);
            }
        } catch (NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this,"El porcentaje debe ser un número válido","Error de formato",0);
            ok = false;
        }
        
            
    }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void rbtnDisminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDisminuirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDisminuirActionPerformed

    private void rbtnAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAumentarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAumentarActionPerformed

    private void txtModTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModTarifaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModTarifaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
this.dispose();    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel lblModTarifa;
    private javax.swing.JRadioButton rbtnAumentar;
    private javax.swing.JRadioButton rbtnDisminuir;
    private javax.swing.JTextField txtModTarifa;
    // End of variables declaration//GEN-END:variables

}